### Word Embedding Techniques using Embedding Layer in Keras

In [39]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1107, 6783, 969, 5871], [1107, 6783, 969, 1032], [1107, 7814, 969, 1435], [1938, 7947, 6021, 3914, 9052], [1938, 7947, 6021, 3914, 9934], [1929, 1107, 5265, 969, 9457], [128, 8851, 3640, 3914]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1107 6783  969 5871]
 [   0    0    0    0 1107 6783  969 1032]
 [   0    0    0    0 1107 7814  969 1435]
 [   0    0    0 1938 7947 6021 3914 9052]
 [   0    0    0 1938 7947 6021 3914 9934]
 [   0    0    0 1929 1107 5265  969 9457]
 [   0    0    0    0  128 8851 3640 3914]]


In [9]:
dim=10


In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 72ms/step
[[[ 0.01355498  0.00384076  0.02870785 -0.01937451  0.02158579
   -0.01578523  0.00062766  0.00099858 -0.02635425 -0.03595325]
  [ 0.01355498  0.00384076  0.02870785 -0.01937451  0.02158579
   -0.01578523  0.00062766  0.00099858 -0.02635425 -0.03595325]
  [ 0.01355498  0.00384076  0.02870785 -0.01937451  0.02158579
   -0.01578523  0.00062766  0.00099858 -0.02635425 -0.03595325]
  [ 0.01355498  0.00384076  0.02870785 -0.01937451  0.02158579
   -0.01578523  0.00062766  0.00099858 -0.02635425 -0.03595325]
  [ 0.03332638 -0.01884116  0.03072314  0.03546708  0.03978082
    0.03867299 -0.0279042   0.02872627 -0.000778   -0.02710776]
  [-0.02713314 -0.03085289 -0.04443007 -0.0318803  -0.00517278
    0.03589744 -0.03054595  0.022431    0.04962119 -0.02095558]
  [-0.04042013 -0.02029427 -0.02004653  0.00384376  0.02735697
    0.04366291  0.03594564 -0.04750918 -0.04888253  0.03494147]
  [-0.02655425  0.04120064  0.00389814 -0.04088736 -0.03424

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 1107, 6783,  969, 5871])

In [14]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 15ms/step
[[ 0.01355498  0.00384076  0.02870785 -0.01937451  0.02158579 -0.01578523
   0.00062766  0.00099858 -0.02635425 -0.03595325]
 [ 0.01355498  0.00384076  0.02870785 -0.01937451  0.02158579 -0.01578523
   0.00062766  0.00099858 -0.02635425 -0.03595325]
 [ 0.01355498  0.00384076  0.02870785 -0.01937451  0.02158579 -0.01578523
   0.00062766  0.00099858 -0.02635425 -0.03595325]
 [ 0.01355498  0.00384076  0.02870785 -0.01937451  0.02158579 -0.01578523
   0.00062766  0.00099858 -0.02635425 -0.03595325]
 [ 0.03332638 -0.01884116  0.03072314  0.03546708  0.03978082  0.03867299
  -0.0279042   0.02872627 -0.000778   -0.02710776]
 [-0.02713314 -0.03085289 -0.04443007 -0.0318803  -0.00517278  0.03589744
  -0.03054595  0.022431    0.04962119 -0.02095558]
 [-0.04042013 -0.02029427 -0.02004653  0.00384376  0.02735697  0.04366291
   0.03594564 -0.04750918 -0.04888253  0.03494147]
 [-0.02655425  0.04120064  0.00389814 -0.04088736 -0.03424058 -0.01163235